### PR TITLE
Fix and unit test for simple executor.

### LINKED ISSUE #175: CpHeader command failure
With the most recent commit (ef95e55f4732e26c83b4a8cb266f21c6897b309c) my build fails almost immediately in a `CpHeader` step with this log:

```
Create product structure
/bin/mkdir -p /Users/ksmiley/Library/Developer/Xcode/DerivedData/Lyft-dvyneupirgclsnggqtgohnrdrmxl/Build/Products/Debug-iphoneos/Alamofire-iOS/Alamofire.framework/Headers

CpHeader /Users/ksmiley/Library/Developer/Xcode/DerivedData/Lyft-dvyneupirgclsnggqtgohnrdrmxl/Build/Products/Debug-iphoneos/Alamofire-iOS/Alamofire.framework/Headers/Alamofire-iOS-umbrella.h '/Users/ksmiley/dev/phoenix/Pods/Alamofire/../Target Support Files/Alamofire-iOS/Alamofire-iOS-umbrella.h'
    cd /Users/ksmiley/dev/phoenix/Pods
    builtin-copy -exclude CVS -exclude .svn -exclude .git -exclude .hg /Users/ksmiley/dev/phoenix/Pods/Alamofire/../Target Support Files/Alamofire-iOS/Alamofire-iOS-umbrella.h /Users/ksmiley/Library/Developer/Xcode/DerivedData/Lyft-dvyneupirgclsnggqtgohnrdrmxl/Build/Products/Debug-iphoneos/Alamofire-iOS/Alamofire.framework/Headers

** BUILD FAILED **

The following build commands failed:
    CpHeader /Users/ksmiley/Library/Developer/Xcode/DerivedData/Lyft-dvyneupirgclsnggqtgohnrdrmxl/Build/Products/Debug-iphoneos/Alamofire-iOS/Alamofire.framework/Headers/Alamofire-iOS-umbrella.h '/Users/ksmiley/dev/phoenix/Pods/Alamofire/../Target Support Files/Alamofire-iOS/Alamofire-iOS-umbrella.h'
(1 failure)
```

I did a quick bisect and determined this is the first commit with this issue. Let me know if I can provide any more info about this!

### PR DESCRIPTION
**Pull request by grp**
Fixes #175 and starts looking into how to test highly integrated components like this.

### CODE REVIEW

File: Libraries/xcexecution/Sources/SimpleExecutor.cpp [hunk 1]
```diff
@@ -258,7 +257,8 @@ performInvocations(
                         processContext->groupID(),
                         processContext->userName(),
                         processContext->groupName());
-                    success = driver->run(&context, filesystem) != 0;
+                    int exitCode = driver->run(&context, filesystem);
+                    success = (exitCode == 0);
```
Comment (grp) [inline Libraries/xcexecution/Sources/SimpleExecutor.cpp]: `==` instead of `!=` fixes the bug.

**Comment by grp** [comment]
The unit test here has a lot of setup code. Ideas for how to shrink that down would be great!

**Comment by grp** [comment]
Ping. This one is more important than usual since it's needed to fix any builds with builtin tools.

File: Libraries/xcformatter/Sources/NullFormatter.cpp [hunk 2]
```diff
@@ -0,0 +1,130 @@
...
+
+#include <xcformatter/NullFormatter.h>
+#include <pbxbuild/Tool/Invocation.h>
+#include <pbxbuild/Build/Context.h>
+
+#include <algorithm>
+
+using xcformatter::NullFormatter;
+
+NullFormatter::
```
Comment (Ktwu) [inline Libraries/xcformatter/Sources/NullFormatter.cpp]: Do you really need to specify an empty constructor / destructor?

File: Libraries/xcexecution/Tests/test_SimpleExecutor.cpp [hunk 3]
```diff
@@ -0,0 +1,145 @@
...
+        std::vector<std::string>(),
+        std::unordered_map<std::string, std::string>(),
+        0,
+        0,
+        "user",
+        "group");
+
+    /* Create test executor. */
+    auto formatter = xcformatter::NullFormatter::Create();
+    std::vector<std::string> const executablePaths = { "/" };
```
Comment (Ktwu) [inline Libraries/xcexecution/Tests/test_SimpleExecutor.cpp]: Sort of weird to define executablePaths in a code chunk that doesn't use it.

File: Libraries/xcexecution/Tests/test_SimpleExecutor.cpp [hunk 4]
```diff
@@ -0,0 +1,145 @@
...
+    auto registry = builtin::Registry::Create({
+        std::static_pointer_cast<builtin::Driver>(std::make_shared<Driver>("builtin-fail", [](process::Context const *context, Filesystem *filesystem) -> int {
+            return 1;
+        })),
+        std::static_pointer_cast<builtin::Driver>(std::make_shared<Driver>("builtin-success", [](process::Context const *context, Filesystem *filesystem) -> int {
+            return 0;
+        })),
+    });
+
+    auto context = process::MemoryContext(
```
Comment (Ktwu) [inline Libraries/xcexecution/Tests/test_SimpleExecutor.cpp]: Thoughts on defaults in the constructor?

File: Libraries/xcexecution/Tests/test_SimpleExecutor.cpp [hunk 5]
```diff
@@ -0,0 +1,145 @@
...
+
+TEST(SimpleExecutor, PropagateToolResult)
+{
+    /* Create in-memory execution environment. */
+    auto filesystem = MemoryFilesystem({
+        MemoryFilesystem::Entry::File("fail-tool", std::vector<uint8_t>()),
+        MemoryFilesystem::Entry::File("success-tool", std::vector<uint8_t>()),
+    });
+
+    auto launcher = process::MemoryLauncher({
```
Comment (Ktwu) [inline Libraries/xcexecution/Tests/test_SimpleExecutor.cpp]: Seems like the lowest hanging fruit for your test setup is to better unify the fake filesystem and the launcher.  Honestly, given the launcher's entries, you could create the filesystem.  Perhaps you can create a test helper function that iterates through a launcher's behavior and creates the filesystem underneath it?

File: Libraries/xcexecution/Sources/SimpleExecutor.cpp (hunk 1 above)
Comment (Ktwu) [inline Libraries/xcexecution/Sources/SimpleExecutor.cpp]: Amazing.  Not really a fan of adding 'int exitCode' since it's used in this one case, but I don't care enough either way.

File: Libraries/xcexecution/Tests/test_SimpleExecutor.cpp [hunk 6]
```diff
@@ -0,0 +1,145 @@
...
+        { "/fail-tool", [](Filesystem *filesystem, process::Context const *context) -> ext::optional<int> {
+            return 1;
+        } },
+        { "/success-tool", [](Filesystem *filesystem, process::Context const *context) -> ext::optional<int> {
+            return 0;
+        } },
+    });
+
+    auto registry = builtin::Registry::Create({
```
Comment (Ktwu) [inline Libraries/xcexecution/Tests/test_SimpleExecutor.cpp]: Can you remind me what a builtin tool represents?  It'd be nice if this code could be slimmed down but I don't have any ideas.

File: Libraries/xcformatter/Sources/NullFormatter.cpp (hunk 2 above)
Comment (grp) [inline Libraries/xcformatter/Sources/NullFormatter.cpp]: Probably not, I think this is because I copied it from the `DefaultFormatter` which has a constructor argument.

File: Libraries/xcexecution/Tests/test_SimpleExecutor.cpp (hunk 6 above)
Comment (grp) [inline Libraries/xcexecution/Tests/test_SimpleExecutor.cpp]: One of the tools starting with `builtin-` you see in builds, like `builtin-copy` or `builtin-infoPlistUtility`.

File: Libraries/xcexecution/Tests/test_SimpleExecutor.cpp (hunk 4 above)
Comment (grp) [inline Libraries/xcexecution/Tests/test_SimpleExecutor.cpp]: I'm wondering what they should be... anything actually *using* these values (especially the user/group ones) is going to fail, so it's relying on this specific code knowing that they aren't used... not sure that's a good thing to put into the API itself.

File: Libraries/xcexecution/Tests/test_SimpleExecutor.cpp (hunk 3 above)
Comment (grp) [inline Libraries/xcexecution/Tests/test_SimpleExecutor.cpp]: Ya, could move these three lines below the `Tool::Invocation` setup. None of them are used until after that, AFAICT.

File: Libraries/xcexecution/Sources/SimpleExecutor.cpp (hunk 1 above)
Comment (grp) [inline Libraries/xcexecution/Sources/SimpleExecutor.cpp]: Made it a little more obvious that it's returning an `int` rather than a `bool`. I already missed the `!= 0` once when it was on the same line. 😶

File: Libraries/xcexecution/Tests/test_SimpleExecutor.cpp (hunk 5 above)
Comment (grp) [inline Libraries/xcexecution/Tests/test_SimpleExecutor.cpp]: Yeah, I'm seeing this more and more in the filesystem too... for example, `isReadable()` is implicitly depending on the user and group (supposedly encapsulated in the the `process::Context`) to know whether the user/group/other permissions apply... and even `createFile()` implicitly uses the process-inherited `umask` for the permissions it sets.

If the process launcher and filesystem were merged, the memory version could treat the process body as the execute aspect of the filesystem entry, I guess! Would need to figure out the coupling that introduces. Even the `SimpleExecutor` runs built-in tools using an in-memory process context but the default filesystem.

Comment (Ktwu) [inline Libraries/xcexecution/Tests/test_SimpleExecutor.cpp]: Sort of out of scope for this patch, yeah? :)

File: Libraries/xcexecution/Tests/test_SimpleExecutor.cpp (hunk 4 above)
Comment (Ktwu) [inline Libraries/xcexecution/Tests/test_SimpleExecutor.cpp]: Hm, yeah, probably not a good thing to use in the API then.

**Comment by Ktwu** [comment]
Recommendation:  do whatever cleanup you'd like to do (like moving `executablePaths`), and I'll review again since this actually fixes a bug.

Cutting down on the unit test setup will be nice in the future, but unifying the filesystem+launcher will take some work (if it's even possible) and shouldn't hold this back.

File: Libraries/xcexecution/Tests/test_SimpleExecutor.cpp (hunk 5 above)
Comment (grp) [inline Libraries/xcexecution/Tests/test_SimpleExecutor.cpp]: Probably 👍

**Comment by Ktwu** [comment]
@sas, @onhachoe:  you two have any good ideas on how to trim down the unit test setup?
